(venv) root@vm-163079:/home/edited_we2/backend/core# sudo systemctl status gunicorn.service
× gunicorn.service - gunicorn daemon
     Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2025-08-12 23:08:24 UTC; 15s ago
TriggeredBy: × gunicorn.socket
    Process: 868167 ExecStart=/home/edited_we2/backend/venv/bin/gunicorn --pythonpath /home/edited_we2/backend --access>
   Main PID: 868167 (code=exited, status=1/FAILURE)
        CPU: 1.580s

Aug 12 23:08:23 vm-163079 gunicorn[868167]:   File "/home/edited_we2/backend/venv/lib/python3.10/site-packages/gunicorn>
Aug 12 23:08:23 vm-163079 gunicorn[868167]:     time.sleep(0.1)
Aug 12 23:08:23 vm-163079 gunicorn[868167]:   File "/home/edited_we2/backend/venv/lib/python3.10/site-packages/gunicorn>
Aug 12 23:08:23 vm-163079 gunicorn[868167]:     self.reap_workers()
Aug 12 23:08:23 vm-163079 gunicorn[868167]:   File "/home/edited_we2/backend/venv/lib/python3.10/site-packages/gunicorn>
Aug 12 23:08:24 vm-163079 gunicorn[868167]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Aug 12 23:08:24 vm-163079 gunicorn[868167]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Aug 12 23:08:24 vm-163079 systemd[1]: gunicorn.service: Main process exited, code=exited, status=1/FAILURE
Aug 12 23:08:24 vm-163079 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
Aug 12 23:08:24 vm-163079 systemd[1]: gunicorn.service: Consumed 1.580s CPU time.
lines 1-18/18 (END)